package com.quickplay.restbot.caze;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.common.collect.Lists;

public class TestCaseResult {

	private List<String> infos = Lists.newLinkedList();	//generated by this test for explaining the test result
	private List<String> errors = Lists.newLinkedList();	//generated by this test for explaining the test result
	private boolean executed = false;
	
	public List<String> getErrors() {
		return this.errors;
	}
	
	final public void addInfo(String msg) {
		this.infos.add(msg);
	}
	
	final public List<String> getInfos() {
		return infos;
	}
	
	public void addError(String errorMessage, Throwable t) {
		
		t.printStackTrace();
		if (t.getCause() != null) {
			t.getCause().printStackTrace();
		}
		errors.add(errorMessage);
	}
	
	final public boolean isPassed() {
		return errors.size()==0;
	}	
	
	@JsonIgnore
	public boolean isExecuted() {
		return executed;
	}

	public void setExecuted() {
		this.executed = true;
	}	
}
